-- ============================================================================
-- Phase 1 — Row-Level Security, the low-privilege application role, and the
-- audit-log immutability guard.
--
-- This is the migration that makes tenant isolation a database-level
-- guarantee rather than an application convention (see
-- docs/architecture/00-OMNIERP-ARCHITECTURE.md, section B). It is written by
-- hand, not generated by Prisma, because Prisma's schema DSL has no concept
-- of roles, RLS policies, or triggers.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- Low-privilege application role.
--
-- The app connects as omnierp_app, never as the migration/owner role
-- (postgres). Table owners and superusers bypass RLS by default in Postgres,
-- so if the app connected as the owner, every RLS policy below would be a
-- no-op. Using a distinct, non-owner, non-superuser role is what makes the
-- policies actually bind.
--
-- The password here matches backend/.env.example for local dev/test only.
-- Production deployments MUST rotate this via a secrets manager, never by
-- re-running this migration.
-- ----------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'omnierp_app') then
    create role omnierp_app with login password 'omnierp_app';
  end if;
end
$$;

grant usage on schema public to omnierp_app;

-- audit_logs: INSERT only — deliberately no UPDATE/DELETE grant, so the
-- append-only guarantee holds even if application code has a bug.
grant select, insert on public.audit_logs to omnierp_app;

-- Every other Phase 1 table: normal CRUD for the app role.
grant select, insert, update, delete on
  public.tenants,
  public.business_groups,
  public.companies,
  public.branches,
  public.departments,
  public.cost_centres,
  public.profit_centres,
  public.warehouses,
  public.users,
  public.roles,
  public.permissions,
  public.role_permissions,
  public.user_company_access,
  public.refresh_tokens
to omnierp_app;

-- ----------------------------------------------------------------------------
-- Row-Level Security — one policy per tenant-scoped table. current_setting
-- is read with the "missing_ok" flag so a connection that never called
-- SET LOCAL app.tenant_id sees an empty string, which matches no tenant_id
-- and therefore returns zero rows (fail closed, not fail open).
-- ----------------------------------------------------------------------------

alter table public.tenants            enable row level security;
alter table public.business_groups    enable row level security;
alter table public.companies          enable row level security;
alter table public.branches           enable row level security;
alter table public.departments        enable row level security;
alter table public.cost_centres       enable row level security;
alter table public.profit_centres     enable row level security;
alter table public.warehouses         enable row level security;
alter table public.users              enable row level security;
alter table public.roles              enable row level security;
alter table public.user_company_access enable row level security;
alter table public.role_permissions   enable row level security;
alter table public.audit_logs         enable row level security;

-- FORCE so the policy also applies to the table owner — belt and suspenders
-- on top of connecting as a non-owner role. (Superusers still bypass RLS
-- regardless of FORCE; that residual bypass is used deliberately and
-- narrowly by the platform connection — see src/common/prisma.)
alter table public.tenants            force row level security;
alter table public.business_groups    force row level security;
alter table public.companies          force row level security;
alter table public.branches           force row level security;
alter table public.departments        force row level security;
alter table public.cost_centres       force row level security;
alter table public.profit_centres     force row level security;
alter table public.warehouses         force row level security;
alter table public.users              force row level security;
alter table public.roles              force row level security;
alter table public.user_company_access force row level security;
alter table public.role_permissions   force row level security;
alter table public.audit_logs         force row level security;

-- tenants has no tenant_id column of its own — a tenant's isolation boundary
-- is its own id.
create policy tenant_isolation on public.tenants
  using (id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.business_groups
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.companies
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.branches
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.departments
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.cost_centres
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.profit_centres
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.warehouses
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.users
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

create policy tenant_isolation on public.roles
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

-- user_company_access has no tenant_id column directly — scope it through
-- the owning user instead.
create policy tenant_isolation on public.user_company_access
  using (
    user_id in (
      select id from public.users
      where tenant_id = nullif(current_setting('app.tenant_id', true), '')
    )
  );

-- role_permissions has no tenant_id column directly — scope it through the
-- owning role instead. permissions itself is a global, non-sensitive catalog
-- (permission codes/descriptions only) and deliberately carries no RLS.
create policy tenant_isolation on public.role_permissions
  using (
    role_id in (
      select id from public.roles
      where tenant_id = nullif(current_setting('app.tenant_id', true), '')
    )
  );

create policy tenant_isolation on public.audit_logs
  using (tenant_id = nullif(current_setting('app.tenant_id', true), ''));

-- refresh_tokens deliberately has NO tenant policy: token lookup happens
-- before a tenant context exists (that's the whole point of a refresh
-- endpoint), so it is scoped by userId/tokenHash equality in application
-- code instead. It carries no business data, only opaque token bookkeeping.

-- ----------------------------------------------------------------------------
-- Audit log: append-only + hash-chained, enforced at the database level
-- (not just by convention or by omitting a grant).
-- ----------------------------------------------------------------------------

create or replace function reject_audit_log_mutation()
returns trigger as $$
begin
  raise exception 'audit_logs is append-only: % is not permitted', tg_op;
end;
$$ language plpgsql;

create trigger trg_reject_audit_log_update
  before update on public.audit_logs
  for each row execute function reject_audit_log_mutation();

create trigger trg_reject_audit_log_delete
  before delete on public.audit_logs
  for each row execute function reject_audit_log_mutation();

create or replace function set_audit_log_row_hash()
returns trigger as $$
declare
  last_hash text;
begin
  select row_hash into last_hash
    from public.audit_logs
    where tenant_id = new.tenant_id
    order by created_at desc, id desc
    limit 1;

  new.prev_row_hash := last_hash;
  new.row_hash := encode(
    digest(
      coalesce(last_hash, '') || '|' ||
      new.tenant_id::text || '|' ||
      coalesce(new.user_id::text, '') || '|' ||
      new.action || '|' ||
      new.entity_type || '|' ||
      coalesce(new.entity_id::text, '') || '|' ||
      coalesce(new.old_value::text, '') || '|' ||
      coalesce(new.new_value::text, '') || '|' ||
      new.created_at::text,
      'sha256'
    ),
    'hex'
  );
  return new;
end;
$$ language plpgsql;

create trigger trg_set_audit_log_row_hash
  before insert on public.audit_logs
  for each row execute function set_audit_log_row_hash();
